[package]
name = "ecc_model_rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Rust RS bindings for ecc_model via pyo3"

[lib]
name = "_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }

